name: Python CI/CD for Notebooks

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Replace with your Python version (e.g., '3.10')

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt jupyter nbconvert nbval

    # Convert Jupyter Notebooks to Python scripts
 #   - name: Convert notebooks to scripts
  #    run: |
   #     mkdir -p converted_scripts
    #    for notebook in $(find . -name "*.ipynb"); do
     #     jupyter nbconvert --to script "$notebook" --output-dir=converted_scripts;
      #  done

    # Lint the converted Python scripts
   # - name: Lint code
    #  run: |
     #   pip install flake8
      #  flake8 converted_scripts

    # Test the notebooks directly with nbval
    - name: Test notebooks
      run: |
        pytest --nbval-lax --sanitize-with sanitize_config.json

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Add deployment steps here
    - name: Deploy
      run: echo "Deployment step (e.g., uploading to a server or triggering a deploy script)"
